spring:
  application:
    name: userservice
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://database:3306/springbootmicroservicesjwtuser?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:${DATABASE_APP_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DATABASE_APP_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 1113
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.security.access.intercept.AbstractSecurityInterceptor: DEBUG

