spring:
  application:
    name: authservice
  datasource:
    url: jdbc:mysql://database:3306/springbootmicroservicesjwtauth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DATABASE_APP_USER}
    password: ${DATABASE_APP_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 1112
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/



logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.security.access.intercept.AbstractSecurityInterceptor: DEBUG
